
import React, { useState } from 'react';
import { generateElectronicLiterature } from './services/geminiService';
import { AppMode, PoetryResponse, Genre, ModificationType } from './types';
import Terminal from './components/Terminal';
import Visualizer from './components/Visualizer';
import GlitchText from './components/GlitchText';
import AmbientSound from './components/AmbientSound';

const App: React.FC = () => {
  const [mode, setMode] = useState<AppMode>(AppMode.TERMINAL);
  const [loading, setLoading] = useState(false);
  const [poem, setPoem] = useState<PoetryResponse | null>(null);
  const [history, setHistory] = useState<PoetryResponse[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [showManifesto, setShowManifesto] = useState(false);
  const [showSidebar, setShowSidebar] = useState(false);
  const [activeTab, setActiveTab] = useState<'text' | 'analysis'>('text');
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [soundEnabled, setSoundEnabled] = useState(false);

  const handleGenerate = async (prompt: string, genre: Genre) => {
    setLoading(true);
    setError(null);
    try {
      const data = await generateElectronicLiterature(prompt, genre);
      setPoem(data);
      setHistory(prev => [data, ...prev]);
      setActiveTab('text');
      setTimeout(() => {
        setMode(AppMode.VISUALIZER);
      }, 1500);
    } catch (err) {
      setError("خطای سیستمی: عدم برقراری ارتباط با هسته مرکزی.");
    } finally {
      setLoading(false);
    }
  };

  const handleRemix = async (modType: ModificationType) => {
    if (!poem) return;
    setLoading(true); 
    setError(null);
    
    setTimeout(async () => {
        try {
          const data = await generateElectronicLiterature(
              poem.title, 
              poem.genre as Genre,
              { type: modType, originalContent: poem.content }
          );
          setPoem(data);
          setHistory(prev => [data, ...prev]);
        } catch (err) {
            console.error(err);
            setError("خطا در بازآفرینی اثر. لطفا مجدد تلاش کنید.");
        } finally {
            setLoading(false);
        }
    }, 100);
  };

  const loadFromHistory = (item: PoetryResponse) => {
      setPoem(item);
      setMode(AppMode.VISUALIZER);
      setShowSidebar(false);
      setActiveTab('text');
      stopSpeech();
  };

  const toggleManifesto = () => setShowManifesto(!showManifesto);

  const processContent = (text: string) => {
    if (!text) return [];
    return text.replace(/\\n/g, '\n').split(/\r?\n/);
  };

  const handleSpeak = () => {
    if (!poem) return;
    if (isSpeaking) {
        stopSpeech();
        return;
    }
    const utterance = new SpeechSynthesisUtterance(poem.title + " \n " + poem.content);
    const voices = window.speechSynthesis.getVoices();
    const faVoice = voices.find(v => v.lang.includes('fa'));
    if (faVoice) utterance.voice = faVoice;
    utterance.lang = 'fa-IR';
    utterance.rate = 0.8;
    utterance.pitch = 0.9;
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    window.speechSynthesis.speak(utterance);
    setIsSpeaking(true);
  };

  const stopSpeech = () => {
    window.speechSynthesis.cancel();
    setIsSpeaking(false);
  };

  const copyToClipboard = () => {
      if(!poem) return;
      const text = `${poem.title}\n\n${poem.content}\n\n-- generated by NoTazrighi`;
      navigator.clipboard.writeText(text);
      const btn = document.getElementById('copy-btn');
      if(btn) {
          const original = btn.innerText;
          btn.innerText = "کپی شد!";
          setTimeout(() => btn.innerText = original, 2000);
      }
  };

  const renderContent = () => {
    switch (mode) {
      case AppMode.TERMINAL:
        return (
          // Added padding-top to ensure title is not hidden behind the fixed/sticky header
          <div className="flex flex-col items-center justify-center min-h-full w-full px-4 pt-32 pb-10 animate-in fade-in duration-700">
            <header className="mb-8 md:mb-12 text-center space-y-4">
              <GlitchText 
                text="نوتزریقی" 
                as="h1" 
                className="text-6xl md:text-9xl font-black tracking-tighter text-white" 
                intensity="high" 
              />
              <p className="text-cyan-400 font-medium text-base md:text-lg tracking-widest uppercase opacity-80">
                کُدَبیات
              </p>
              <div className="flex items-center justify-center gap-2 mt-4">
                  <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                  <span className="text-xs text-green-500/80 font-mono" dir="ltr">ONLINE :: v5.0</span>
              </div>
            </header>
            <Terminal onGenerate={handleGenerate} onShowManifesto={() => setShowManifesto(true)} isGenerating={loading} />
            {error && <div className="mt-6 text-red-400 bg-red-950/30 border border-red-900/50 px-6 py-3 rounded-lg text-sm shadow-lg mb-10">{error}</div>}
          </div>
        );

      case AppMode.VISUALIZER:
        if (!poem) return <div className="text-center text-gray-500 mt-20">داده‌ای بارگذاری نشده است.</div>;
        return (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 w-full lg:h-full p-4 lg:p-6 animate-in slide-in-from-bottom-4 duration-700 pb-20 lg:pb-6">
            
            {/* Right Column: Text & Analysis (RTL) */}
            <div className="lg:col-span-5 flex flex-col h-[600px] lg:h-full order-2 lg:order-1 glass-panel rounded-2xl shadow-2xl overflow-hidden relative border-t-2 border-t-cyan-500/50">
              
              {/* Header Info */}
              <div className="p-6 pb-2 border-b border-white/5 bg-black/20 shrink-0">
                  <div className="flex justify-between items-start mb-4">
                     <div>
                        <span className="text-xs font-bold text-cyan-400 border border-cyan-500/20 bg-cyan-900/10 px-2 py-1 rounded-md mb-2 inline-block">
                            {poem.genre}
                        </span>
                        <h2 className="text-2xl md:text-3xl lg:text-4xl font-black text-white leading-tight">
                            {poem.title}
                        </h2>
                     </div>
                     <div className="flex gap-2">
                         <button 
                            onClick={handleSpeak}
                            className={`p-2 rounded-full transition-all border border-white/5 ${isSpeaking ? 'bg-red-500/20 text-red-400 animate-pulse border-red-500/30' : 'bg-white/5 text-gray-400 hover:text-white hover:bg-white/10'}`}
                            title="خوانش صوتی"
                         >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                                {isSpeaking ? (
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                ) : (
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M19.114 5.636a9 9 0 010 12.728M16.463 8.288a5.25 5.25 0 010 7.424M6.75 8.25l4.72-4.72a.75.75 0 011.28.53v15.88a.75.75 0 01-1.28.53l-4.72-4.72H4.51c-.88 0-1.704-.507-1.938-1.354A9.01 9.01 0 012.25 12c0-.83.112-1.633.322-2.396C2.806 8.756 3.63 8.25 4.51 8.25H6.75z" />
                                )}
                            </svg>
                         </button>
                         <button
                            id="copy-btn"
                            onClick={copyToClipboard}
                            className="p-2 rounded-full bg-white/5 text-gray-400 hover:text-white hover:bg-white/10 border border-white/5 transition-all text-xs w-20"
                         >
                             کپی
                         </button>
                     </div>
                  </div>
                  
                  {/* Tabs */}
                  <div className="flex gap-4 text-sm mt-4">
                      <button 
                        onClick={() => setActiveTab('text')}
                        className={`pb-2 transition-colors relative ${activeTab === 'text' ? 'text-white' : 'text-gray-500 hover:text-gray-300'}`}
                      >
                        متن اثر
                        {activeTab === 'text' && <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-cyan-500 shadow-[0_0_8px_rgba(6,182,212,0.8)]"></span>}
                      </button>
                      <button 
                        onClick={() => setActiveTab('analysis')}
                        className={`pb-2 transition-colors relative ${activeTab === 'analysis' ? 'text-white' : 'text-gray-500 hover:text-gray-300'}`}
                      >
                        تحلیل نوتزریقی
                        {activeTab === 'analysis' && <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-purple-500 shadow-[0_0_8px_rgba(168,85,247,0.8)]"></span>}
                      </button>
                  </div>
              </div>

              {/* Scrollable Content */}
              <div className="flex-1 overflow-y-auto custom-scrollbar p-6 bg-gradient-to-b from-black/20 to-transparent relative">
                 {loading && (
                     <div className="absolute inset-0 bg-black/70 backdrop-blur-sm z-30 flex items-center justify-center">
                         <div className="flex flex-col items-center gap-3">
                             <div className="w-8 h-8 border-2 border-cyan-500 border-t-transparent rounded-full animate-spin"></div>
                             <span className="text-cyan-400 text-sm animate-pulse">بازآفرینی کُدَبیات...</span>
                         </div>
                     </div>
                 )}
                {activeTab === 'text' ? (
                     <div className="prose prose-invert prose-lg max-w-none">
                        {processContent(poem.content).map((line, idx) => (
                        <p key={`${poem.id}-${idx}`} className={`leading-9 text-gray-200 font-light text-justify transition-opacity duration-500 ${line.trim() === '' ? 'h-8' : ''}`}>
                            {line}
                        </p>
                        ))}
                    </div>
                ) : (
                    <div className="space-y-4 animate-in fade-in slide-in-from-right-4 duration-300">
                        <div className="p-5 bg-purple-900/10 border border-purple-500/20 rounded-xl relative overflow-hidden">
                            <div className="absolute top-0 right-0 w-1 h-full bg-purple-500/50"></div>
                            <h4 className="text-purple-400 font-bold mb-3 text-sm flex items-center gap-2">
                                <span className="w-2 h-2 bg-purple-500 rounded-full"></span>
                                تحلیل هوشمند
                            </h4>
                            <p className="text-gray-300 text-sm leading-8 text-justify pl-2">
                                {poem.analysis}
                            </p>
                        </div>
                        <div className="mt-6">
                            <h4 className="text-gray-500 text-xs font-bold mb-3">شبکه معنایی:</h4>
                            <div className="flex flex-wrap gap-2">
                                {poem.keywords.map((kw, i) => (
                                    <span key={i} className="text-xs bg-gray-800/50 text-gray-400 px-3 py-1.5 rounded-full border border-gray-700/50 hover:border-cyan-500/30 hover:text-cyan-400 transition-colors cursor-default">
                                        #{kw}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>
                )}
              </div>

              {/* Footer Actions (Remix) */}
              <div className="p-4 bg-black/40 border-t border-white/5 shrink-0">
                <p className="text-[10px] text-gray-500 mb-2 font-bold">بازآفرینی و تزریق مجدد:</p>
                <div className="flex gap-2 overflow-x-auto pb-1 custom-scrollbar">
                    {Object.values(ModificationType).map((mod) => (
                        <button
                            key={mod}
                            onClick={() => handleRemix(mod)}
                            disabled={loading}
                            className="whitespace-nowrap px-3 py-2 bg-white/5 hover:bg-white/10 text-gray-300 hover:text-white rounded border border-white/10 text-xs transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {mod}
                        </button>
                    ))}
                </div>
              </div>
            </div>

            {/* Left Column: Visualizer */}
            <div className="lg:col-span-7 h-[400px] lg:h-full order-1 lg:order-2 flex flex-col gap-4">
                <Visualizer data={poem} />
                <div className="hidden lg:flex h-24 glass-panel rounded-xl p-4 overflow-hidden relative flex-col justify-between shrink-0">
                    <div className="absolute top-2 right-2 text-[10px] text-gray-500 font-mono">SYSTEM_LOGS</div>
                    <div className="text-xs text-green-500/60 font-mono space-y-1 mt-2 opacity-70" dir="ltr">
                        <p>{`> ID: ${poem.id.split('-')[0]}...`}</p>
                        <p>{`> GENRE: ${poem.genre}`}</p>
                        <p>{`> IMG_GEN: ${poem.imageBase64 ? 'SUCCESS' : 'PENDING'}`}</p>
                    </div>
                    <div className="flex justify-end">
                         <button 
                            onClick={() => { stopSpeech(); setMode(AppMode.TERMINAL); }}
                            className="text-xs bg-cyan-900/20 text-cyan-400 border border-cyan-500/30 px-4 py-2 rounded hover:bg-cyan-900/40 transition-colors"
                         >
                             شروع جدید &larr;
                         </button>
                    </div>
                </div>
                {/* Mobile Reset Button */}
                <div className="lg:hidden flex justify-center">
                    <button 
                       onClick={() => { stopSpeech(); setMode(AppMode.TERMINAL); }}
                       className="text-sm bg-cyan-900/20 text-cyan-400 border border-cyan-500/30 px-6 py-2 rounded hover:bg-cyan-900/40 transition-colors w-full"
                    >
                        شروع جدید
                    </button>
                </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="h-[100dvh] bg-[#080808] text-gray-200 selection:bg-cyan-500/30 selection:text-white relative flex flex-col" dir="rtl">
        
        <AmbientSound isPlaying={soundEnabled} />

        {/* Ambient Background */}
        <div className="fixed inset-0 pointer-events-none z-0">
             <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-cyan-900/10 rounded-full blur-[120px] animate-pulse duration-[4000ms]"></div>
             <div className="absolute bottom-[-10%] right-[-10%] w-[600px] h-[600px] bg-purple-900/10 rounded-full blur-[150px] animate-pulse duration-[7000ms]"></div>
             <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-full h-full bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iMiIgY3k9IjIiIHI9IjEiIGZpbGw9InJnYmEoMjU1LCAyNTUsIDI1NSwgMC4wNSkiLz48L3N2Zz4=')] opacity-30"></div>
        </div>

        {/* Navbar */}
        <nav className="h-20 w-full px-6 flex justify-between items-center backdrop-blur-sm bg-black/20 border-b border-white/5 z-40 shrink-0 sticky top-0">
            <div className="flex items-center gap-4">
                <div 
                    className="w-10 h-10 bg-gradient-to-tr from-cyan-600 to-blue-700 rounded-lg flex items-center justify-center cursor-pointer shadow-[0_0_15px_rgba(6,182,212,0.5)] group relative overflow-hidden"
                    onClick={() => { stopSpeech(); setMode(AppMode.TERMINAL); }}
                >
                    <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                    <span className="font-bold text-white text-xl relative z-10">N</span>
                </div>
                <div className="hidden md:flex flex-col">
                    <span className="font-bold text-white text-lg tracking-wide leading-none">نوتزریقی</span>
                    <span className="text-[10px] text-cyan-500 tracking-wider">کُدَبیات</span>
                </div>
            </div>
            
            <div className="flex items-center gap-3 md:gap-4">
                <button
                    onClick={() => setSoundEnabled(!soundEnabled)}
                    className={`p-2 rounded-full transition-all border ${soundEnabled ? 'text-cyan-400 border-cyan-500/50 bg-cyan-900/20' : 'text-gray-500 border-transparent hover:bg-white/5'}`}
                    title="صدای محیط"
                >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                      {soundEnabled ? (
                          <path strokeLinecap="round" strokeLinejoin="round" d="M19.114 5.636a9 9 0 010 12.728M16.463 8.288a5.25 5.25 0 010 7.424M6.75 8.25l4.72-4.72a.75.75 0 011.28.53v15.88a.75.75 0 01-1.28.53l-4.72-4.72H4.51c-.88 0-1.704-.507-1.938-1.354A9.01 9.01 0 012.25 12c0-.83.112-1.633.322-2.396C2.806 8.756 3.63 8.25 4.51 8.25H6.75z" />
                      ) : (
                          <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 9.75L19.5 12m0 0l2.25 2.25M19.5 12l2.25-2.25M19.5 12l-2.25 2.25m-10.5-6l4.72-4.72a.75.75 0 011.28.53v15.88a.75.75 0 01-1.28.53l-4.72-4.72H4.51c-.88 0-1.704-.507-1.938-1.354A9.01 9.01 0 012.25 12c0-.83.112-1.633.322-2.396C2.806 8.756 3.63 8.25 4.51 8.25H6.75z" />
                      )}
                    </svg>
                </button>
                <div className="h-6 w-px bg-white/10 mx-1"></div>
                <button 
                    onClick={() => setShowSidebar(true)}
                    className="text-sm font-medium text-gray-400 hover:text-white transition-colors flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-white/5"
                >
                    <span>آرشیو</span>
                    <span className="bg-gray-800 text-gray-300 text-[10px] px-2 py-0.5 rounded-full min-w-[20px] text-center">{history.length}</span>
                </button>
                <button 
                    onClick={toggleManifesto}
                    className="text-sm font-medium text-gray-400 hover:text-white transition-colors px-3 py-1.5 rounded-md hover:bg-white/5 hidden md:block"
                >
                    مانیفست
                </button>
            </div>
        </nav>

        {/* Sidebar History */}
        <div className={`fixed inset-y-0 left-0 w-80 bg-[#0c0c0c]/95 backdrop-blur-xl border-r border-white/10 z-50 transform transition-transform duration-500 cubic-bezier(0.16, 1, 0.3, 1) shadow-2xl ${showSidebar ? 'translate-x-0' : '-translate-x-full'}`}>
             <div className="p-6 h-full flex flex-col">
                <div className="flex justify-between items-center mb-8 border-b border-white/10 pb-4">
                    <h3 className="text-xl font-bold text-white">آرشیو نشست</h3>
                    <button onClick={() => setShowSidebar(false)} className="text-gray-500 hover:text-red-400 transition-colors text-2xl leading-none">&times;</button>
                </div>
                <div className="flex-1 overflow-y-auto space-y-3 custom-scrollbar">
                    {history.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-40 text-gray-600 space-y-2 opacity-50">
                             <div className="w-10 h-10 border-2 border-gray-700 border-dashed rounded-full animate-spin-slow"></div>
                             <p className="text-sm">هنوز اثری خلق نشده است.</p>
                        </div>
                    ) : (
                        history.map(item => (
                            <div 
                                key={item.id} 
                                onClick={() => loadFromHistory(item)}
                                className={`p-4 rounded-lg cursor-pointer transition-all border group relative overflow-hidden ${poem?.id === item.id ? 'bg-cyan-900/20 border-cyan-500/50' : 'bg-white/5 border-transparent hover:border-white/20'}`}
                            >
                                <div className={`absolute left-0 top-0 bottom-0 w-1 ${poem?.id === item.id ? 'bg-cyan-500' : 'bg-transparent group-hover:bg-white/20'}`}></div>
                                <h4 className="font-bold text-gray-200 text-sm mb-1 truncate">{item.title}</h4>
                                <div className="flex justify-between text-[10px] text-gray-500 mt-2">
                                    <span>{item.genre}</span>
                                    <span>{new Date(item.createdAt).toLocaleTimeString('fa-IR', {hour: '2-digit', minute: '2-digit'})}</span>
                                </div>
                            </div>
                        ))
                    )}
                </div>
             </div>
        </div>

        {/* Manifesto Modal */}
        {showManifesto && (
            <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-300">
                <div className="bg-[#111] border border-white/10 rounded-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto relative shadow-2xl">
                    <button 
                        onClick={toggleManifesto}
                        className="absolute top-4 left-4 text-gray-400 hover:text-white transition-colors w-8 h-8 flex items-center justify-center rounded-full hover:bg-white/10"
                    >
                        ✕
                    </button>
                    <div className="p-8 md:p-12 text-center">
                        <GlitchText text="مانیفست نوتزریقی" as="h2" className="text-3xl font-black mb-8 text-white" intensity="medium" />
                        <div className="space-y-6 text-gray-300 leading-8 font-light text-justify">
                            <p>
                                <strong className="text-cyan-400">از تزریق صفوی تا نوتزریقی دیجیتال:</strong><br/>
                                در عصر صفوی، شاعران «تزریق‌گو» با آگاهی و طنازی، شعر بی‌معنی می‌سرودند تا ساختارهای منطقی زبان را به چالش بکشند. آن یک «بی‌معنایی آگاهانه» بود.
                            </p>
                            <p>
                                اما اینجا، در <strong className="text-purple-400">نوتزریقی</strong>، ما با «بی‌معنایی ناآگاهانه» ماشین روبرو هستیم. هوش مصنوعی در غیاب آگاهی (Consciousness)، واژگان را تزریق می‌کند.
                            </p>
                            <p>
                                طبق نظریه کاترین هیلز (N. Katherine Hayles)، ما در اینجا یک «همبسته شناختی» (Cognitive Assemblage) می‌سازیم. ماشین متن را تولید می‌کند، اما این «انسان» است که با خواندن آن، معنا را در خلاء تزریق می‌کند. نوتزریقی، رقص میان پوچی ماشین و معناسازی ذهن انسان است.
                            </p>
                            <p className="text-sm opacity-70 mt-4 border-t border-white/10 pt-4">
                                "ما معنا را کشف نمی‌کنیم، ما آن را به رگ‌های کُد تزریق می‌کنیم."
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        )}

        {/* Main Content Container with correct height calculation and scroll */}
        <main className="relative z-10 flex-1 overflow-y-auto custom-scrollbar" style={{ height: 'calc(100dvh - 80px)' }}>
            {renderContent()}
        </main>
    </div>
  );
};

export default App;
